# Generated by Django 4.2.1 on 2023-07-04 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='greetings',
        ),
    ]
