# Generated by Django 4.2.1 on 2023-07-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcard', '0002_remove_home_greetings'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_image', models.ImageField(upload_to='about/images')),
                ('projects_completed', models.IntegerField(default=0)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('happy_clients', models.IntegerField(default=0)),
                ('customer_reviews', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField(default=50)),
            ],
        ),
    ]
