# Generated by Django 4.2.1 on 2023-07-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcard', '0003_about_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_year', models.IntegerField()),
                ('finished_year', models.CharField(default='Present', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
