# Generated by Django 4.2.1 on 2023-07-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcard', '0006_portfolio_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('fetaured_image', models.ImageField(upload_to='blog/images')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
