# Generated by Django 4.2.1 on 2023-07-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcard', '0007_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='fetaured_image',
            new_name='featured_image',
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
