# Generated by Django 4.2.1 on 2023-07-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcard', '0008_rename_fetaured_image_blog_featured_image_blog_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_link', models.URLField(max_length=255)),
                ('media_icon', models.CharField(default='fab fa-facebook-f', max_length=100)),
            ],
        ),
    ]
